### PR TITLE
Add 'delete line' button next to each row

### PR DESCRIPTION
**Pull request by bloodypenguin**
A row now looks like this:

http://screencast.com/t/NZlFG7X9wwkB

A click on the button deletes the line.

### CODE REVIEW

**Comment by justacid** [comment]
Hi there - sorry I didn't comment yet. I'll review it within the next few days. Thanks! :)

**Comment by bloodypenguin** [comment]
Hi! Have you had a chance to review my pull request?

**Comment by justacid** [comment]
Sorry, I've been really busy - I'll get to it tomorrow, thanks for your patience.

**Comment by justacid** [comment]
Allright, looks good, I'm merging it. Sorry it took so long.

**Comment by bloodypenguin** [comment]
NP. BTW, I'm BloodyPenguin in Steam :)

**Pull request merged**
