### PR TITLE
Make mod multi-lingual

### PR DESCRIPTION
**Pull request by dmantione**
Dear AcidFire,

I'm a happy user of your mod. After creating a Dutch language mod for Cities Skylines, I was looking at your mod and your mod still puts English texts on the screen. So I spent a few yours modifying your mod to allow it to become multi-lingual and did some translation.

This patch makes your mod multi-lingual and contains Dutch, German and Italian. For Dutch and Italian mods need to be installed to see the effect.

Would you accept this patch in your mod?

Best regards,

Daniël Mantione

### CODE REVIEW

**Comment by justacid** [comment]
Hi there, sorry I'm getting back to you this late - I've been on holidays!
Anyway, I really like the idea of making the mod multi-lingual (it never occurred to me, even though I'm German myself :laughing: ) - I'm not entirely happy with having the languages hard coded, but I think that suffices for a start... I'm probably going to fix up some formatting and if everything goes fine I'd merge it the next few days - thank you for your work!

PS: Could you link the Dutch and Italian language mods so I can test them? Thanks. :)

**Comment by dmantione** [comment]
Hallo Tobias,

Kein Problem, des Laben besteht aus mehr dann Computerspiele :)

Meine Niederländische Übersetzungsmod kannst du hier finden:

http://steamcommunity.com/sharedfiles/filedetails/?id=517574710

Die Italiënische Übersetzung is nicht im Workshop verfügfbar (zumindest, nu eine serh alte). Das Prozedur ist, um in diesem Forum in diesem Forum für den Download zu fragen. Ein bisschen kompliziert, aber weil ich auch Italienisch spreche, habe ich es auch auf Italienisch übersetst.

http://www.citiesskylines.it/phpbb/viewtopic.php?f=17&t=25

Was betrifft die Hardcoding, es wurde Ideal sein, .locale Dateien zu machen, wie das Spiel selbst sie nutzt. Ich weisse jedoch nicht ob dass möglich ist, Hardcoding ist ist derzeit die einzige Alternative. Ich habe auch einen Patch für den Difficulty Tuning Mod gemacht. Der Autor davon hat noch etwas an dem Code gebastelt, vielleicht gefällt seine Version dir besser:

https://github.com/ZenyaIse/Cities-Skyline-Difficulty-Tuning-Mod/blob/master/Source/Language.cs

?

Grüsse,

Daniël

**Comment by justacid** [comment]
I started working on your PR and I guess it will take longer than I hoped - I refactored the code a little and made it possible to reload the language without reloading the game. Problem is how to handle the layout - it should update itself when changing the language so that everything fits but currently everything is hardcoded and looks really ugly when changing languages. I might need to write something like a UITable component with auto fitting... but I have no idea when I've got some time for that - any ideas?

**Comment by dmantione** [comment]
Hello Tobias,

I spent some time on it... it was harder than I thought. The game's locale manager has a eventLocaleChanged event:

http://static.croxford.me/CitiesSkylinesAPIDOC/ColossalFramework.Globalization/LocaleManager.html

The UICaptionContainer might register an event handler for this and then update its column widths when this happens. I did some coding on it, but didn't get it working for now.

Daniël

**Pull request closed without merging**
