### PR TITLE
Add ability to sort transport lines by each column

### PR DESCRIPTION
**Pull request by leeclemens**
Sort columns (ascending) when the column name is clicked

### CODE REVIEW

**Comment by leeclemens** [comment]
This is my first C# code, and it uses reflection so it's not super efficient.  Known bug (room for improvement): Rows are not resorted when values update (ideally would only re-sort if value in particular column is updated).

**Comment by justacid** [comment]
Thanks for your pull request - I'm going to review it within the next few days!

**Comment by leeclemens** [comment]
Thanks!  I used MonoDevelop on Linux, so I had to change a few platform dependent things and the `ToolsVersion` (https://unix.stackexchange.com/questions/119701/how-to-open-visual-studio-2013-solution-in-monodevelop) to get it to build.

**Comment by justacid** [comment]
Hi there, I just merged your pullrequest (with some minor fixups, and disabling linename trimming again, since it kills fps like crazy because of all the string operations - I'll need to rewrite that part some time) - I'm not entirely happy with using reflection, but I believe it's good enough for now.

**Pull request merged**
